# Generated by Django 5.0.6 on 2024-06-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(null=True)),
                ('funçao', models.TextField(null=True)),
                ('admissao', models.DateField(null=True)),
                ('demissao', models.DateField(blank=True, null=True)),
                ('tipo', models.TextField(null=True)),
                ('diaria', models.IntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
