# Generated by Django 5.0.6 on 2024-06-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lançamento_obra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'managed': False},
        ),
    ]
