# Generated by Django 5.0.6 on 2024-07-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lançamento_obra', '0002_alter_atividade_options_alter_colaborador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoJunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('colaborador', models.CharField(blank=True, max_length=255, null=True)),
                ('obra', models.IntegerField(blank=True, null=True)),
                ('uteis', models.DurationField(blank=True, null=True)),
                ('naoutil', models.BigIntegerField(blank=True, null=True)),
                ('total_he50', models.DurationField(blank=True, null=True)),
                ('total_he100', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resumo_junta',
                'managed': False,
            },
        ),
    ]
