# Generated by Django 5.0.6 on 2024-06-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lançamento_obra', '0002_alter_colaborador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={},
        ),
    ]
