# Generated by Django 5.0.6 on 2024-08-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idr', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('action', models.CharField(max_length=10)),
                ('context', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'historico',
                'managed': True,
            },
        ),
    ]
