# Generated by Django 5.0.6 on 2024-07-19 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaSalas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sala', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('responsavel', models.CharField()),
                ('reservado', models.CharField(blank=True, null=True)),
                ('hora', models.CharField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agenda_salas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('tipo', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'atividade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('admissao', models.DateField(blank=True, null=True)),
                ('demissao', models.DateField(blank=True, null=True)),
                ('diaria', models.TextField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, null=True)),
                ('contrato', models.CharField(max_length=20)),
                ('encarregado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'colaborador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('dia', models.DateField(primary_key=True, serialize=False)),
                ('diasemana', models.IntegerField()),
                ('feriado', models.BooleanField()),
                ('programacao', models.DateField()),
            ],
            options={
                'db_table': 'dia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diarioobra',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('obra', models.IntegerField(blank=True, null=True)),
                ('encarregado', models.CharField(blank=True, max_length=100, null=True)),
                ('climamanha', models.CharField(blank=True, max_length=20, null=True)),
                ('climatarde', models.CharField(blank=True, max_length=20, null=True)),
                ('imagem', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'diarioobra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=100)),
                ('grupo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'funcao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idr', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('action', models.CharField(max_length=50)),
                ('context', models.CharField()),
            ],
            options={
                'db_table': 'historico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Indiceobra',
            fields=[
                ('indice', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indiceobra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JuntaPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('colaborador', models.CharField(blank=True, max_length=255, null=True)),
                ('atestado', models.DurationField(blank=True, null=True)),
                ('atividade_obra', models.DurationField(blank=True, null=True)),
                ('dispensa', models.DurationField(blank=True, null=True)),
                ('falta', models.DurationField(blank=True, null=True)),
                ('ferias', models.DurationField(blank=True, null=True)),
                ('folga', models.DurationField(blank=True, null=True)),
                ('treinamento', models.DurationField(blank=True, null=True)),
                ('he100', models.IntegerField(blank=True, null=True)),
                ('he50', models.IntegerField(blank=True, null=True)),
                ('hn', models.IntegerField(blank=True, null=True)),
                ('obra', models.IntegerField(blank=True, null=True)),
                ('ate2', models.DurationField(blank=True, null=True)),
                ('atv2', models.DurationField(blank=True, null=True)),
                ('d2', models.DurationField(blank=True, null=True)),
                ('fl2', models.DurationField(blank=True, null=True)),
                ('fe2', models.DurationField(blank=True, null=True)),
                ('fo2', models.DurationField(blank=True, null=True)),
                ('tr2', models.DurationField(blank=True, null=True)),
                ('totalmax', models.DurationField(blank=True, null=True)),
                ('totalparc', models.DurationField(blank=True, null=True)),
                ('uteis', models.DurationField(blank=True, null=True)),
                ('he_100', models.DurationField(blank=True, null=True)),
                ('he_50', models.DurationField(blank=True, null=True)),
                ('hesaldo', models.DurationField(blank=True, null=True)),
                ('dcid', models.TextField(blank=True, null=True)),
                ('iddcid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'junta_por_dia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LancIncompletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('total_horas', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lanc_incompletos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('cr', models.IntegerField(primary_key=True, serialize=False)),
                ('orcamento', models.CharField(max_length=20)),
                ('retrabalho', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=500, null=True)),
                ('finalizada', models.BooleanField()),
                ('indice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'obra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResumoJunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, null=True)),
                ('colaborador', models.CharField(blank=True, max_length=255, null=True)),
                ('obra', models.IntegerField(blank=True, null=True)),
                ('uteis', models.DurationField(blank=True, null=True)),
                ('naoutil', models.BigIntegerField(blank=True, null=True)),
                ('total_he50', models.DurationField(blank=True, null=True)),
                ('total_he100', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resumo_junta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'salas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisor', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField()),
            ],
            options={
                'db_table': 'supervisor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipocontrato',
            fields=[
                ('contrato', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipocontrato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('cr', models.IntegerField(primary_key=True, serialize=False)),
                ('etapa', models.IntegerField()),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'etapa',
                'managed': True,
                'unique_together': {('cr', 'etapa')},
            },
        ),
        migrations.CreateModel(
            name='Lancamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.CharField(max_length=255)),
                ('dia', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=600, null=True)),
                ('digito', models.IntegerField()),
                ('diaseguinte', models.BooleanField()),
                ('horaini1', models.TimeField()),
                ('horafim1', models.TimeField()),
                ('horaini2', models.TimeField(blank=True, null=True)),
                ('horafim2', models.TimeField(blank=True, null=True)),
                ('horaini3', models.TimeField(blank=True, null=True)),
                ('horafim3', models.TimeField(blank=True, null=True)),
                ('perdevale', models.BooleanField(blank=True, null=True)),
                ('revisaorh', models.CharField(blank=True, max_length=255, null=True)),
                ('etapa1', models.IntegerField(blank=True, null=True)),
                ('etapa2', models.IntegerField(blank=True, null=True)),
                ('etapa3', models.IntegerField(blank=True, null=True)),
                ('diario', models.CharField(blank=True, max_length=30, null=True)),
                ('atividade', models.ForeignKey(db_column='atividade', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.atividade')),
                ('obra', models.ForeignKey(db_column='obra', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.obra')),
            ],
            options={
                'db_table': 'lancamentos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_column='supervisor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.supervisor'),
        ),
        migrations.CreateModel(
            name='Localizacaoprogramada',
            fields=[
                ('colaborador', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('iniciosemana', models.DateField()),
                ('encarregado', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('obra', models.ForeignKey(db_column='obra', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.obra')),
            ],
            options={
                'db_table': 'localizacaoprogramada',
                'managed': True,
                'unique_together': {('colaborador', 'iniciosemana', 'obra')},
            },
        ),
    ]
