name: Django [TESTE] CI / DEPLOY

on:
  push:
    branches: [ "teste" ]


jobs:
  deploy:
    runs-on: self-hosted  # O runner self-hosted está no servidor de produção
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    env:
      branch: teste
      app: front
    defaults:
      run:
        working-directory: /home/tecnika/bat
    steps:
      # Deploy no servidor de produção
    - name: Finalizando servidor
      run: sudo bash django-stop.sh $branch $app #Fecha os serviços do django

    - name: Atualizando o servidor
      run: sudo bash django-update.sh $branch $app #Faz a atualização das dependencia e arquivos
      
    - name: Coletando estáticos
      working-directory: /home/tecnika/TK/django/teste/front
      run: python3 manage.py collectstatic --noinput

    - name: Reiniciando servidor
      run: sudo bash django-reload.sh $branch $app #Reinicia o processo do django

