name: Django [TESTE] TESTE / DEPLOY

on:
  push:
    branches: [ "teste" ]


jobs:
  # test:
  #   runs-on: self-hosted  # O runner self-hosted está no servidor de produção
  #   strategy:
  #     max-parallel: 4
  #     matrix:
  #       python-version: [3.12]
  #   steps:
  #   - uses: actions/checkout@v4  # Faz o checkout do código fonte

  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}

  #   - name: Create virtual environment
  #     run: python -m venv venv  # Cria o ambiente virtual localmente no servidor de produção

  #   - name: Install Dependencies
  #     run: |
  #       source venv/bin/activate
  #       pip install -r requirements.txt

  #   - name: Copiando .env
  #     run: cp /home/tecnika/TK/django/env/teste_front.env .env
      
  #   - name: Run Tests
  #     run: |
  #       source venv/bin/activate  
  #       python manage.py test
        
  deploy:
    # needs: test
    runs-on: self-hosted  # O runner self-hosted está no servidor de produção
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    env:
      branch: teste
      app: front
    defaults:
      run:
        working-directory: /home/tecnika/TK/django/teste/front

    steps:
      # Deploy no servidor de produção
    - name: Finalizando servidor
      working-directory: /home/tecnika/bat
      run: sudo bash django-stop.sh $branch $app #Fecha os serviços do django

    - name: Atualizando arquivos
      run: sudo git pull origin $branch --force
      
    - name: Baixando bibliotecas
      run: |
        source venv/bin/activate
        pip install -r requirements.txt
        
        
    - name: Copiando .env
      run: cp /home/tecnika/TK/django/env/teste_front.env .env

    - name: Coletando estáticos
      run: python3 manage.py collectstatic --noinput
  
    - name: Iniciando servidor
      working-directory: /home/tecnika/bat
      run: sudo bash django-reload.sh $branch $app #Reinicia o processo do django


