name: Django [TESTE] CI / DEPLOY

on:
  push:
    branches: [ "teste" ]
  pull_request:
    branches: [ "teste" ]

jobs:
  build-and-deploy:

    runs-on: self-hosted  # O runner self-hosted está no servidor de produção
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4  # Faz o checkout do código fonte

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: python -m venv venv  # Cria o ambiente virtual localmente no servidor de produção

    - name: Install Dependencies
      run: |
        source venv/bin/activate  # Ativa o ambiente virtual
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências

    - name: Run Tests
      run: |
        source venv/bin/activate  # Ativa o ambiente virtual
        python manage.py test  # Roda os testes

    # Deploy no servidor de produção
    - name: Deploy to Production
      if: success()  # Só faz o deploy se os testes passarem
      run: |
        cd /home/tecnika
        bash bat/django-update.sh teste front
        bash bat/django-reload.sh teste