name: Django [TESTE] CI / DEPLOY

on:
  push:
    branches: [ "teste" ]
  pull_request:
    branches: [ "teste" ]

jobs:
  test:
    runs-on: self-hosted  # O runner self-hosted está no servidor de produção
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4  # Faz o checkout do código fonte

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create virtual environment
      run: python -m venv venv  # Cria o ambiente virtual localmente no servidor de produção

    - name: Install Dependencies
      run: |
        source venv/bin/activate  # Ativa o ambiente virtual
        pip install --use-feature=fast-deps -r requirements.txt  # Instala as dependências

    - name: Run Tests
      run: |
        source venv/bin/activate  # Ativa o ambiente virtual
        python manage.py test  # Roda os testes

  deploy:
    needs: test
    runs-on: self-hosted  # O runner self-hosted está no servidor de produção
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    env:
      branch: teste
      app: front
    defaults:
      run:
        shell: bash
        working-directory: /home/tecnika/bat
    steps:
      # Deploy no servidor de produção
    - name: Finalizando servidor
      run: sudo bash django-stop.sh $branch $app #Fecha os serviços do django

    - name: Atualizando o servidor
      run: sudo bash django-update.sh $branch $app #Faz a atualização das dependencia e arquivos
      
    - name: Coletando estáticos
      working-directory: /home/tecnika/TK/django/$branch/$app
      run: python manage.py collectstatic

    - name: Reiniciando servidor
      run: sudo bash django-reload.sh $branch $app #Reinicia o processo do django

